version: '2.3'
services:
  monster-ui-builder:
    container_name: monster-ui-builder
    build:
      context: .
      args:
        MONSTER_UI_VERSION: 4.1.56
        MONSTER_APP_ACCOUNTS_VERSION: 4.1.6
        MONSTER_APP_CALLFLOWS_VERSION: 4.1.37
        MONSTER_APP_FAX_VERSION: 4.1.5
        MONSTER_APP_NUMBERS_VERSION: 4.1.2
        MONSTER_APP_PBXS_VERSION: 4.1.6
        MONSTER_APP_VOIP_VERSION: 4.1.21
        MONSTER_APP_VOICEMAILS_VERSION: 4.1.6
        MONSTER_APP_WEBHOOKS_VERSION: 4.1.5
        NODE_VERSION: "6"
    image: "telephoneorg/monster-ui-builder:${TAG:-latest}"
    volumes:
    - $PWD/dist:/dist
