FROM    telephoneorg/debian:stretch

MAINTAINER Joe Black <me@joeblack.nyc>

ARG     MONSTER_UI_VERSION
ARG     MONSTER_APPS
ARG     MONSTER_APP_ACCOUNTS_VERSION
ARG     MONSTER_APP_CALLFLOWS_VERSION
ARG     MONSTER_APP_FAX_VERSION
ARG     MONSTER_APP_NUMBERS_VERSION
ARG     MONSTER_APP_PBXS_VERSION
ARG     MONSTER_APP_VOIP_VERSION
ARG     MONSTER_APP_VOICEMAILS_VERSION
ARG     MONSTER_APP_WEBHOOKS_VERSION
ARG     NODE_VERSION

ENV     MONSTER_UI_VERSION=${MONSTER_UI_VERSION:-4.1.53}
ENV     MONSTER_APPS=${MONSTER_APPS:-accounts,callflows,fax,numbers,pbxs,voip,voicemails,webhooks}
ENV     MONSTER_APP_ACCOUNTS_VERSION=${MONSTER_APP_ACCOUNTS_VERSION:-4.1.6}
ENV     MONSTER_APP_CALLFLOWS_VERSION=${MONSTER_APP_CALLFLOWS_VERSION:-4.1.36}
ENV     MONSTER_APP_FAX_VERSION=${MONSTER_APP_FAX_VERSION:-4.1.5}
ENV     MONSTER_APP_NUMBERS_VERSION=${MONSTER_APP_NUMBERS_VERSION:-4.1.2}
ENV     MONSTER_APP_PBXS_VERSION=${MONSTER_APP_PBXS_VERSION:-4.1.6}
ENV     MONSTER_APP_VOIP_VERSION=${MONSTER_APP_VOIP_VERSION:-4.1.20}
ENV     MONSTER_APP_VOICEMAILS_VERSION=${MONSTER_APP_VOICEMAILS_VERSION:-4.1.6}
ENV     MONSTER_APP_WEBHOOKS_VERSION=${MONSTER_APP_WEBHOOKS_VERSION:-4.1.5}
ENV     NODE_VERSION=${NODE_VERSION:-6}

LABEL   monster.ui.version=$MONSTER_UI_VERSION
LABEL   monster.apps.installed=$MONSTER_APPS
LABEL   monster.app.accounts.version=$MONSTER_APP_ACCOUNTS_VERSION
LABEL   monster.app.callflows.version=$MONSTER_APP_CALLFLOWS_VERSION
LABEL   monster.app.fax.version=$MONSTER_APP_FAX_VERSION
LABEL   monster.app.numbers.version=$MONSTER_APP_NUMBERS_VERSION
LABEL   monster.app.pbxs.version=$MONSTER_APP_PBXS_VERSION
LABEL   monster.app.voip.version=$MONSTER_APP_VOIP_VERSION
LABEL   monster.app.voicemails.version=$MONSTER_APP_VOICEMAILS_VERSION
LABEL   monster.app.webhooks.version=$MONSTER_APP_WEBHOOKS_VERSION

ENV     APP monster-ui
ENV     USER $APP
ENV     HOME /build
WORKDIR $HOME

COPY    build-builder.sh /tmp/
RUN     /tmp/build-builder.sh

VOLUME  ["/dist"]

COPY    build-monster-ui.sh /

CMD     ["/build-monster-ui.sh"]
